/*\n  # Create AI Chat History System\n\n  1. New Tables\n    - `ai_chat_sessions`\n      - `id` (uuid, primary key)\n      - `user_id` (uuid, foreign key to profiles)\n      - `started_at` (timestamptz)\n      - `ended_at` (timestamptz, nullable)\n      - `message_count` (integer)\n    \n    - `ai_chat_messages`\n      - `id` (uuid, primary key)\n      - `session_id` (uuid, foreign key to ai_chat_sessions)\n      - `user_id` (uuid, foreign key to profiles)\n      - `role` (text, 'user' or 'assistant')\n      - `content` (text)\n      - `audio_used` (boolean)\n      - `created_at` (timestamptz)\n\n  2. Security\n    - Enable RLS on both tables\n    - Users can only access their own chat history\n    - Users can insert their own messages\n*/\n\n-- Create ai_chat_sessions table\nCREATE TABLE IF NOT EXISTS ai_chat_sessions (\n  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),\n  user_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,\n  started_at TIMESTAMPTZ DEFAULT now(),\n  ended_at TIMESTAMPTZ,\n  message_count INTEGER DEFAULT 0,\n  created_at TIMESTAMPTZ DEFAULT now()\n);
\n\n-- Create ai_chat_messages table\nCREATE TABLE IF NOT EXISTS ai_chat_messages (\n  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),\n  session_id UUID NOT NULL REFERENCES ai_chat_sessions(id) ON DELETE CASCADE,\n  user_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,\n  role TEXT NOT NULL CHECK (role IN ('user', 'assistant')),\n  content TEXT NOT NULL,\n  audio_used BOOLEAN DEFAULT false,\n  created_at TIMESTAMPTZ DEFAULT now()\n);
\n\n-- Create indexes for better query performance\nCREATE INDEX IF NOT EXISTS idx_ai_chat_sessions_user_id ON ai_chat_sessions(user_id);
\nCREATE INDEX IF NOT EXISTS idx_ai_chat_sessions_started_at ON ai_chat_sessions(started_at DESC);
\nCREATE INDEX IF NOT EXISTS idx_ai_chat_messages_session_id ON ai_chat_messages(session_id);
\nCREATE INDEX IF NOT EXISTS idx_ai_chat_messages_created_at ON ai_chat_messages(created_at DESC);
\n\n-- Enable RLS\nALTER TABLE ai_chat_sessions ENABLE ROW LEVEL SECURITY;
\nALTER TABLE ai_chat_messages ENABLE ROW LEVEL SECURITY;
\n\n-- Drop existing policies if they exist\nDROP POLICY IF EXISTS "Users can view own chat sessions" ON ai_chat_sessions;
\nDROP POLICY IF EXISTS "Users can insert own chat sessions" ON ai_chat_sessions;
\nDROP POLICY IF EXISTS "Users can update own chat sessions" ON ai_chat_sessions;
\nDROP POLICY IF EXISTS "Users can view own chat messages" ON ai_chat_messages;
\nDROP POLICY IF EXISTS "Users can insert own chat messages" ON ai_chat_messages;
\n\n-- RLS Policies for ai_chat_sessions\nCREATE POLICY "Users can view own chat sessions"\n  ON ai_chat_sessions\n  FOR SELECT\n  TO authenticated\n  USING (auth.uid() = user_id);
\n\nCREATE POLICY "Users can insert own chat sessions"\n  ON ai_chat_sessions\n  FOR INSERT\n  TO authenticated\n  WITH CHECK (auth.uid() = user_id);
\n\nCREATE POLICY "Users can update own chat sessions"\n  ON ai_chat_sessions\n  FOR UPDATE\n  TO authenticated\n  USING (auth.uid() = user_id)\n  WITH CHECK (auth.uid() = user_id);
\n\n-- RLS Policies for ai_chat_messages\nCREATE POLICY "Users can view own chat messages"\n  ON ai_chat_messages\n  FOR SELECT\n  TO authenticated\n  USING (auth.uid() = user_id);
\n\nCREATE POLICY "Users can insert own chat messages"\n  ON ai_chat_messages\n  FOR INSERT\n  TO authenticated\n  WITH CHECK (auth.uid() = user_id);
\n\n-- Function to update message count\nCREATE OR REPLACE FUNCTION update_session_message_count()\nRETURNS TRIGGER AS $$\nBEGIN\n  UPDATE ai_chat_sessions\n  SET message_count = message_count + 1\n  WHERE id = NEW.session_id;
\n  RETURN NEW;
\nEND;
\n$$ LANGUAGE plpgsql;
\n\n-- Trigger to auto-update message count\nDROP TRIGGER IF EXISTS trigger_update_session_message_count ON ai_chat_messages;
\nCREATE TRIGGER trigger_update_session_message_count\n  AFTER INSERT ON ai_chat_messages\n  FOR EACH ROW\n  EXECUTE FUNCTION update_session_message_count();
\n;
