/*\n  # Create Order Automatically on Booking Insert\n  \n  This migration creates a trigger that automatically creates an order when a booking is created.\n  This ensures that orders are always created immediately when a booking is made, regardless of payment method.\n  \n  ## What it does:\n  \n  1. Creates a function `create_order_for_booking()` that:\n     - Gets the partner's commission percentage\n     - Calculates IVA, commission, and partner amounts\n     - Creates partner_breakdown JSON structure\n     - Inserts a new order with all required fields\n     - Sets order status based on payment method (pending for payment_link, confirmed for others)\n  \n  2. Creates a trigger `booking_create_order` that:\n     - Fires AFTER INSERT on bookings table\n     - Calls the create_order_for_booking() function\n     - Only creates order if one doesn't already exist for this booking\n  \n  ## Important Notes:\n  \n  - Orders created via payment_link will have status 'pending' until payment is confirmed\n  - Orders created via cash/card/transfer will have status 'confirmed' immediately\n  - The webhook will update the order with payment details when payment is received\n  - The IVA rate is set to 22%\n  - Commission percentage comes from the partner's record, defaulting to 5% if not set\n*/\n\n-- Create function to automatically create an order when a booking is created\nCREATE OR REPLACE FUNCTION create_order_for_booking()\nRETURNS TRIGGER AS $$\nDECLARE\n  v_commission_percentage NUMERIC;
\n  v_commission_amount NUMERIC;
\n  v_partner_amount NUMERIC;
\n  v_iva_amount NUMERIC;
\n  v_partner_breakdown JSONB;
\n  v_order_status TEXT;
\n  v_payment_status TEXT;
\n  v_iva_rate NUMERIC := 22;
\nBEGIN\n  -- Check if order already exists for this booking\n  IF EXISTS (SELECT 1 FROM orders WHERE booking_id = NEW.id) THEN\n    RETURN NEW;
\n  END IF;
\n\n  -- Get partner commission percentage\n  SELECT commission_percentage INTO v_commission_percentage\n  FROM partners\n  WHERE id = NEW.partner_id;
\n\n  -- Default to 5% if not set\n  v_commission_percentage := COALESCE(v_commission_percentage, 5);
\n\n  -- Calculate amounts\n  v_commission_amount := (NEW.total_amount * v_commission_percentage) / 100;
\n  v_partner_amount := NEW.total_amount - v_commission_amount;
\n  v_iva_amount := (NEW.total_amount * v_iva_rate) / 100;
\n\n  -- Set order status based on payment method\n  IF NEW.payment_method = 'payment_link' THEN\n    v_order_status := 'pending';
\n    v_payment_status := 'pending';
\n  ELSE\n    v_order_status := 'confirmed';
\n    v_payment_status := COALESCE(NEW.payment_status, 'approved');
\n  END IF;
\n\n  -- Build partner breakdown JSON\n  v_partner_breakdown := jsonb_build_object(\n    'iva_rate', v_iva_rate,\n    'partners', jsonb_build_object(\n      NEW.partner_id::text, jsonb_build_object(\n        'items', jsonb_build_array(\n          jsonb_build_object(\n            'id', COALESCE(NEW.service_id::text, NEW.id::text),\n            'name', COALESCE(NEW.service_name, 'Servicio'),\n            'price', NEW.total_amount,\n            'total', NEW.total_amount,\n            'quantity', 1,\n            'subtotal', NEW.total_amount,\n            'iva_amount', v_iva_amount\n          )\n        ),\n        'subtotal', NEW.total_amount,\n        'partner_id', NEW.partner_id,\n        'partner_name', COALESCE(NEW.partner_name, 'Partner')\n      )\n    ),\n    'iva_amount', v_iva_amount,\n    'iva_included', false,\n    'shipping_cost', 0,\n    'total_partners', 1,\n    'commission_split', v_commission_amount\n  );
\n\n  -- Create the order\n  INSERT INTO orders (\n    partner_id,\n    customer_id,\n    booking_id,\n    order_type,\n    service_id,\n    pet_id,\n    status,\n    total_amount,\n    subtotal,\n    iva_rate,\n    iva_amount,\n    iva_included_in_price,\n    shipping_cost,\n    commission_amount,\n    partner_amount,\n    partner_breakdown,\n    partner_name,\n    service_name,\n    pet_name,\n    customer_name,\n    customer_email,\n    customer_phone,\n    appointment_date,\n    appointment_time,\n    payment_method,\n    payment_status,\n    payment_preference_id,\n    payment_data,\n    booking_notes,\n    items\n  ) VALUES (\n    NEW.partner_id,\n    NEW.customer_id,\n    NEW.id,\n    'service_booking',\n    NEW.service_id,\n    NEW.pet_id,\n    v_order_status,\n    NEW.total_amount,\n    NEW.total_amount,\n    v_iva_rate,\n    v_iva_amount,\n    false,\n    0,\n    v_commission_amount,\n    v_partner_amount,\n    v_partner_breakdown,\n    NEW.partner_name,\n    NEW.service_name,\n    NEW.pet_name,\n    NEW.customer_name,\n    NEW.customer_email,\n    NEW.customer_phone,\n    NEW.date,\n    NEW.time,\n    COALESCE(NEW.payment_method, 'cash'),\n    v_payment_status,\n    NEW.payment_preference_id,\n    NEW.payment_data,\n    NEW.notes,\n    jsonb_build_array(\n      jsonb_build_object(\n        'id', COALESCE(NEW.service_id::text, NEW.id::text),\n        'name', COALESCE(NEW.service_name, 'Servicio'),\n        'price', NEW.total_amount,\n        'quantity', 1\n      )\n    )\n  );
\n\n  RETURN NEW;
\nEND;
\n$$ LANGUAGE plpgsql SECURITY DEFINER;
\n\n-- Create trigger to automatically create order when booking is created\nDROP TRIGGER IF EXISTS booking_create_order ON bookings;
\nCREATE TRIGGER booking_create_order\n  AFTER INSERT ON bookings\n  FOR EACH ROW\n  EXECUTE FUNCTION create_order_for_booking();
\n;
