/*\n  # Add Order Number System\n  \n  Creates a complete order number generation system for orders and bookings.\n  \n  ## Changes:\n  \n  1. New Sequence\n     - `order_number_seq`: Sequential counter for order numbers\n  \n  2. New Function\n     - `generate_order_number()`: Generates unique order numbers in format ORD-YYYYMMDD-XXX\n  \n  3. New Triggers\n     - Automatically generates order_number when orders are created\n     - Updates booking with order_number when order is created\n  \n  4. Schema Updates\n     - Adds `order_number` column to bookings table\n     - Updates existing orders with generated order numbers\n  \n  ## Order Number Format:\n  \n  Format: ORD-20260206-001\n  - ORD: Prefix for orders\n  - YYYYMMDD: Date of creation\n  - XXX: Sequential number for that day (resets daily)\n  \n  ## Security:\n  \n  - Function runs as SECURITY DEFINER to ensure all users can generate numbers\n  - Triggers run automatically on insert\n*/\n\n-- Create sequence for order numbers\nCREATE SEQUENCE IF NOT EXISTS order_number_seq START 1;
\n\n-- Add order_number to bookings table if it doesn't exist\nDO $$\nBEGIN\n  IF NOT EXISTS (\n    SELECT 1 FROM information_schema.columns\n    WHERE table_name = 'bookings' AND column_name = 'order_number'\n  ) THEN\n    ALTER TABLE bookings ADD COLUMN order_number TEXT;
\n  END IF;
\nEND $$;
\n\n-- Function to generate unique order number\nCREATE OR REPLACE FUNCTION generate_order_number()\nRETURNS TEXT AS $$\nDECLARE\n  v_date TEXT;
\n  v_seq INTEGER;
\n  v_order_number TEXT;
\nBEGIN\n  -- Get current date in YYYYMMDD format\n  v_date := to_char(CURRENT_DATE, 'YYYYMMDD');
\n  \n  -- Get next sequence number for today\n  -- Check how many orders were created today\n  SELECT COUNT(*) + 1 INTO v_seq\n  FROM orders\n  WHERE DATE(created_at) = CURRENT_DATE;
\n  \n  -- Generate order number: ORD-YYYYMMDD-XXX\n  v_order_number := 'ORD-' || v_date || '-' || LPAD(v_seq::TEXT, 3, '0');
\n  \n  RETURN v_order_number;
\nEND;
\n$$ LANGUAGE plpgsql SECURITY DEFINER;
\n\n-- Trigger function to set order_number on orders\nCREATE OR REPLACE FUNCTION set_order_number()\nRETURNS TRIGGER AS $$\nBEGIN\n  -- Only generate if order_number is not already set\n  IF NEW.order_number IS NULL THEN\n    NEW.order_number := generate_order_number();
\n  END IF;
\n  RETURN NEW;
\nEND;
\n$$ LANGUAGE plpgsql;
\n\n-- Create trigger for orders\nDROP TRIGGER IF EXISTS trigger_set_order_number ON orders;
\nCREATE TRIGGER trigger_set_order_number\n  BEFORE INSERT ON orders\n  FOR EACH ROW\n  EXECUTE FUNCTION set_order_number();
\n\n-- Update create_order_for_booking function to also set order_number on booking\nCREATE OR REPLACE FUNCTION create_order_for_booking()\nRETURNS TRIGGER AS $$\nDECLARE\n  v_commission_percentage NUMERIC;
\n  v_commission_amount NUMERIC;
\n  v_partner_amount NUMERIC;
\n  v_iva_amount NUMERIC;
\n  v_partner_breakdown JSONB;
\n  v_order_status TEXT;
\n  v_payment_status TEXT;
\n  v_iva_rate NUMERIC := 22;
\n  v_partner_rut TEXT;
\n  v_partner_email TEXT;
\n  v_partner_phone TEXT;
\n  v_partner_address TEXT;
\n  v_items JSONB;
\n  v_order_number TEXT;
\n  v_order_id UUID;
\nBEGIN\n  -- Check if order already exists for this booking\n  IF EXISTS (SELECT 1 FROM orders WHERE booking_id = NEW.id) THEN\n    RETURN NEW;
\n  END IF;
\n\n  -- Generate order number\n  v_order_number := generate_order_number();
\n\n  -- Get partner data including fiscal information\n  SELECT \n    commission_percentage,\n    rut,\n    email,\n    phone,\n    address\n  INTO \n    v_commission_percentage,\n    v_partner_rut,\n    v_partner_email,\n    v_partner_phone,\n    v_partner_address\n  FROM partners\n  WHERE id = NEW.partner_id;
\n\n  -- Default to 5% if commission not set\n  v_commission_percentage := COALESCE(v_commission_percentage, 5);
\n\n  -- Calculate amounts\n  v_commission_amount := (NEW.total_amount * v_commission_percentage) / 100;
\n  v_partner_amount := NEW.total_amount - v_commission_amount;
\n  v_iva_amount := (NEW.total_amount * v_iva_rate) / 100;
\n\n  -- Set order status based on payment method\n  IF NEW.payment_method = 'payment_link' THEN\n    v_order_status := 'pending';
\n    v_payment_status := 'pending';
\n  ELSE\n    v_order_status := 'confirmed';
\n    v_payment_status := COALESCE(NEW.payment_status, 'approved');
\n  END IF;
\n\n  -- Build complete items array with all accounting fields\n  v_items := jsonb_build_array(\n    jsonb_build_object(\n      'id', COALESCE(NEW.service_id::text, NEW.id::text),\n      'name', COALESCE(NEW.service_name, 'Servicio'),\n      'type', 'service',\n      'price', NEW.total_amount,\n      'currency', 'UYU',\n      'currency_code_dgi', '858',\n      'iva_rate', v_iva_rate,\n      'quantity', 1,\n      'subtotal', NEW.total_amount,\n      'iva_amount', v_iva_amount,\n      'partnerId', NEW.partner_id,\n      'partnerName', COALESCE(NEW.partner_name, 'Partner'),\n      'partner_name', COALESCE(NEW.partner_name, 'Partner'),\n      'original_price', NEW.total_amount,\n      'discount_percentage', 0\n    )\n  );
\n\n  -- Build partner breakdown JSON with fiscal data\n  v_partner_breakdown := jsonb_build_object(\n    'iva_rate', v_iva_rate,\n    'partners', jsonb_build_object(\n      NEW.partner_id::text, jsonb_build_object(\n        'partner_id', NEW.partner_id,\n        'partner_name', COALESCE(NEW.partner_name, 'Partner'),\n        'partner_rut', v_partner_rut,\n        'partner_email', v_partner_email,\n        'partner_phone', v_partner_phone,\n        'partner_address', v_partner_address,\n        'items', jsonb_build_array(\n          jsonb_build_object(\n            'id', COALESCE(NEW.service_id::text, NEW.id::text),\n            'name', COALESCE(NEW.service_name, 'Servicio'),\n            'price', NEW.total_amount,\n            'total', NEW.total_amount,\n            'quantity', 1,\n            'subtotal', NEW.total_amount,\n            'iva_amount', v_iva_amount\n          )\n        ),\n        'subtotal', NEW.total_amount\n      )\n    ),\n    'iva_amount', v_iva_amount,\n    'iva_included', false,\n    'shipping_cost', 0,\n    'total_partners', 1,\n    'commission_split', v_commission_amount\n  );
\n\n  -- Create the order with complete items structure and order_number\n  INSERT INTO orders (\n    partner_id,\n    customer_id,\n    booking_id,\n    order_type,\n    service_id,\n    pet_id,\n    status,\n    total_amount,\n    subtotal,\n    iva_rate,\n    iva_amount,\n    iva_included_in_price,\n    shipping_cost,\n    commission_amount,\n    partner_amount,\n    partner_breakdown,\n    partner_name,\n    service_name,\n    pet_name,\n    customer_name,\n    customer_email,\n    customer_phone,\n    appointment_date,\n    appointment_time,\n    payment_method,\n    payment_status,\n    payment_preference_id,\n    payment_data,\n    booking_notes,\n    items,\n    order_number\n  ) VALUES (\n    NEW.partner_id,\n    NEW.customer_id,\n    NEW.id,\n    'service_booking',\n    NEW.service_id,\n    NEW.pet_id,\n    v_order_status,\n    NEW.total_amount,\n    NEW.total_amount,\n    v_iva_rate,\n    v_iva_amount,\n    false,\n    0,\n    v_commission_amount,\n    v_partner_amount,\n    v_partner_breakdown,\n    NEW.partner_name,\n    NEW.service_name,\n    NEW.pet_name,\n    NEW.customer_name,\n    NEW.customer_email,\n    NEW.customer_phone,\n    NEW.date,\n    NEW.time,\n    COALESCE(NEW.payment_method, 'cash'),\n    v_payment_status,\n    NEW.payment_preference_id,\n    NEW.payment_data,\n    NEW.notes,\n    v_items,\n    v_order_number\n  ) RETURNING id INTO v_order_id;
\n\n  -- Update the booking with the order_number\n  UPDATE bookings\n  SET order_number = v_order_number\n  WHERE id = NEW.id;
\n\n  RETURN NEW;
\nEND;
\n$$ LANGUAGE plpgsql SECURITY DEFINER;
\n\n-- Update existing orders with order numbers (backwards compatibility)\nDO $$\nDECLARE\n  v_order RECORD;
\n  v_order_number TEXT;
\n  v_counter INTEGER := 0;
\nBEGIN\n  FOR v_order IN SELECT id, created_at FROM orders WHERE order_number IS NULL ORDER BY created_at\n  LOOP\n    v_counter := v_counter + 1;
\n    v_order_number := 'ORD-' || to_char(v_order.created_at, 'YYYYMMDD') || '-' || LPAD(v_counter::TEXT, 3, '0');
\n    \n    UPDATE orders \n    SET order_number = v_order_number \n    WHERE id = v_order.id;
\n    \n    -- Also update the corresponding booking if it exists\n    UPDATE bookings \n    SET order_number = v_order_number \n    WHERE id = (SELECT booking_id FROM orders WHERE id = v_order.id);
\n  END LOOP;
\nEND $$;
\n;
