/*\n  # Update Order Trigger to Include Partner Fiscal Data\n  \n  Updates the create_order_for_booking() function to include complete partner fiscal information\n  in the partner_breakdown JSON. This prevents the send-order-to-accounting function from having\n  to make additional queries to get partner details.\n  \n  ## Changes:\n  \n  1. Fetches additional partner data (RUT, email, phone, address) from partners table\n  2. Includes this data in the partner_breakdown JSON structure\n  3. This ensures all data needed by accounting systems is available in the order\n  \n  ## Partner Breakdown Structure:\n  \n  ```json\n  {\n    "iva_rate": 22,\n    "partners": {\n      "partner-uuid": {\n        "partner_id": "partner-uuid",\n        "partner_name": "Partner Name",\n        "partner_rut": "123456789012",\n        "partner_email": "partner@example.com",\n        "partner_phone": "099123456",\n        "partner_address": "Street 123",\n        "items": [...],\n        "subtotal": 350\n      }\n    },\n    "iva_amount": 77,\n    "iva_included": false,\n    "shipping_cost": 0,\n    "total_partners": 1,\n    "commission_split": 17.5\n  }\n  ```\n*/\n\n-- Update function to include partner fiscal data in breakdown\nCREATE OR REPLACE FUNCTION create_order_for_booking()\nRETURNS TRIGGER AS $$\nDECLARE\n  v_commission_percentage NUMERIC;
\n  v_commission_amount NUMERIC;
\n  v_partner_amount NUMERIC;
\n  v_iva_amount NUMERIC;
\n  v_partner_breakdown JSONB;
\n  v_order_status TEXT;
\n  v_payment_status TEXT;
\n  v_iva_rate NUMERIC := 22;
\n  v_partner_rut TEXT;
\n  v_partner_email TEXT;
\n  v_partner_phone TEXT;
\n  v_partner_address TEXT;
\nBEGIN\n  -- Check if order already exists for this booking\n  IF EXISTS (SELECT 1 FROM orders WHERE booking_id = NEW.id) THEN\n    RETURN NEW;
\n  END IF;
\n\n  -- Get partner data including fiscal information\n  SELECT \n    commission_percentage,\n    rut,\n    email,\n    phone,\n    address\n  INTO \n    v_commission_percentage,\n    v_partner_rut,\n    v_partner_email,\n    v_partner_phone,\n    v_partner_address\n  FROM partners\n  WHERE id = NEW.partner_id;
\n\n  -- Default to 5% if commission not set\n  v_commission_percentage := COALESCE(v_commission_percentage, 5);
\n\n  -- Calculate amounts\n  v_commission_amount := (NEW.total_amount * v_commission_percentage) / 100;
\n  v_partner_amount := NEW.total_amount - v_commission_amount;
\n  v_iva_amount := (NEW.total_amount * v_iva_rate) / 100;
\n\n  -- Set order status based on payment method\n  IF NEW.payment_method = 'payment_link' THEN\n    v_order_status := 'pending';
\n    v_payment_status := 'pending';
\n  ELSE\n    v_order_status := 'confirmed';
\n    v_payment_status := COALESCE(NEW.payment_status, 'approved');
\n  END IF;
\n\n  -- Build partner breakdown JSON with fiscal data\n  v_partner_breakdown := jsonb_build_object(\n    'iva_rate', v_iva_rate,\n    'partners', jsonb_build_object(\n      NEW.partner_id::text, jsonb_build_object(\n        'partner_id', NEW.partner_id,\n        'partner_name', COALESCE(NEW.partner_name, 'Partner'),\n        'partner_rut', v_partner_rut,\n        'partner_email', v_partner_email,\n        'partner_phone', v_partner_phone,\n        'partner_address', v_partner_address,\n        'items', jsonb_build_array(\n          jsonb_build_object(\n            'id', COALESCE(NEW.service_id::text, NEW.id::text),\n            'name', COALESCE(NEW.service_name, 'Servicio'),\n            'price', NEW.total_amount,\n            'total', NEW.total_amount,\n            'quantity', 1,\n            'subtotal', NEW.total_amount,\n            'iva_amount', v_iva_amount\n          )\n        ),\n        'subtotal', NEW.total_amount\n      )\n    ),\n    'iva_amount', v_iva_amount,\n    'iva_included', false,\n    'shipping_cost', 0,\n    'total_partners', 1,\n    'commission_split', v_commission_amount\n  );
\n\n  -- Create the order\n  INSERT INTO orders (\n    partner_id,\n    customer_id,\n    booking_id,\n    order_type,\n    service_id,\n    pet_id,\n    status,\n    total_amount,\n    subtotal,\n    iva_rate,\n    iva_amount,\n    iva_included_in_price,\n    shipping_cost,\n    commission_amount,\n    partner_amount,\n    partner_breakdown,\n    partner_name,\n    service_name,\n    pet_name,\n    customer_name,\n    customer_email,\n    customer_phone,\n    appointment_date,\n    appointment_time,\n    payment_method,\n    payment_status,\n    payment_preference_id,\n    payment_data,\n    booking_notes,\n    items\n  ) VALUES (\n    NEW.partner_id,\n    NEW.customer_id,\n    NEW.id,\n    'service_booking',\n    NEW.service_id,\n    NEW.pet_id,\n    v_order_status,\n    NEW.total_amount,\n    NEW.total_amount,\n    v_iva_rate,\n    v_iva_amount,\n    false,\n    0,\n    v_commission_amount,\n    v_partner_amount,\n    v_partner_breakdown,\n    NEW.partner_name,\n    NEW.service_name,\n    NEW.pet_name,\n    NEW.customer_name,\n    NEW.customer_email,\n    NEW.customer_phone,\n    NEW.date,\n    NEW.time,\n    COALESCE(NEW.payment_method, 'cash'),\n    v_payment_status,\n    NEW.payment_preference_id,\n    NEW.payment_data,\n    NEW.notes,\n    jsonb_build_array(\n      jsonb_build_object(\n        'id', COALESCE(NEW.service_id::text, NEW.id::text),\n        'name', COALESCE(NEW.service_name, 'Servicio'),\n        'price', NEW.total_amount,\n        'quantity', 1\n      )\n    )\n  );
\n\n  RETURN NEW;
\nEND;
\n$$ LANGUAGE plpgsql SECURITY DEFINER;
\n;
