/*\n  # Sync Bookings with Confirmed Orders\n  \n  ## Problem:\n  Bookings remain in "pending" status even though their associated orders are "confirmed".\n  This happens when payments are processed through MercadoPago webhooks.\n  \n  ## Solution:\n  1. **Data Fix**: Update all bookings that have confirmed orders but pending status\n  2. **Trigger**: Create a trigger to automatically sync booking status when order status changes\n  \n  ## Changes Made:\n  \n  1. Data Synchronization\n     - Updates all bookings with pending status that have confirmed orders\n     - Copies payment details from orders to bookings\n  \n  2. New Trigger Function\n     - `sync_booking_status_on_order_update()`: Automatically updates booking status when order changes\n  \n  3. New Trigger\n     - Fires AFTER UPDATE on orders table\n     - Syncs booking status, payment_status, and payment_method with order\n  \n  ## Security:\n  - Trigger runs as SECURITY DEFINER to ensure proper permissions\n  - Only syncs when order status actually changes\n*/\n\n-- Update all bookings that have confirmed orders but are still pending\nUPDATE bookings b\nSET \n  status = o.status,\n  payment_status = o.payment_status,\n  payment_method = COALESCE(b.payment_method, o.payment_method),\n  payment_id = COALESCE(b.payment_id, o.payment_id),\n  payment_data = COALESCE(b.payment_data, o.payment_data),\n  payment_confirmed_at = COALESCE(b.payment_confirmed_at, o.updated_at)\nFROM orders o\nWHERE o.booking_id = b.id\n  AND o.status = 'confirmed'\n  AND b.status != 'confirmed';
\n\n-- Create trigger function to sync booking status when order is updated\nCREATE OR REPLACE FUNCTION sync_booking_status_on_order_update()\nRETURNS TRIGGER AS $$\nBEGIN\n  -- Only proceed if status actually changed\n  IF OLD.status IS DISTINCT FROM NEW.status OR \n     OLD.payment_status IS DISTINCT FROM NEW.payment_status THEN\n    \n    -- Update the associated booking\n    UPDATE bookings\n    SET \n      status = NEW.status,\n      payment_status = NEW.payment_status,\n      payment_method = COALESCE(bookings.payment_method, NEW.payment_method),\n      payment_id = COALESCE(bookings.payment_id, NEW.payment_id),\n      payment_data = COALESCE(bookings.payment_data, NEW.payment_data),\n      payment_confirmed_at = CASE \n        WHEN NEW.status = 'confirmed' AND bookings.payment_confirmed_at IS NULL \n        THEN NEW.updated_at \n        ELSE bookings.payment_confirmed_at \n      END,\n      updated_at = NOW()\n    WHERE id = NEW.booking_id;
\n    \n  END IF;
\n  \n  RETURN NEW;
\nEND;
\n$$ LANGUAGE plpgsql SECURITY DEFINER;
\n\n-- Create trigger to sync booking status when order is updated\nDROP TRIGGER IF EXISTS trigger_sync_booking_on_order_update ON orders;
\nCREATE TRIGGER trigger_sync_booking_on_order_update\n  AFTER UPDATE ON orders\n  FOR EACH ROW\n  WHEN (OLD.status IS DISTINCT FROM NEW.status OR OLD.payment_status IS DISTINCT FROM NEW.payment_status)\n  EXECUTE FUNCTION sync_booking_status_on_order_update();
\n;
