import React, { createContext, useContext, useState, useEffect } from 'react';
import AsyncStorage from '@react-native-async-storage/async-storage';

type Language = 'es' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  es: {
    // Navigation
    home: 'Inicio',
    myPets: 'Mascotas',
    shop: 'Tienda',
    services: 'Servicios',
    petFriendly: 'Pet Friendly',
    profile: 'Perfil',
    
    // Auth
    welcomeBack: '¡Bienvenido de vuelta a Patitas! 🐾',
    signInSubtitle: 'Inicia sesión para conectar con tu comunidad de mascotas',
    joinPatitas: '¡Únete a Patitas! 🐾',
    createAccountSubtitle: 'Crea tu cuenta y comienza a conectar con amantes de las mascotas',
    email: 'Correo electrónico',
    password: 'Contraseña',
    confirmPassword: 'Confirmar contraseña',
    fullName: 'Nombre completo',
    signIn: 'Iniciar sesión',
    signUp: 'Registrarse',
    createAccount: 'Crear cuenta',
    becomePartner: 'Convertirme en aliado',
    partnerRegisterSubtitle: 'Crea tu cuenta de aliado para acceder al panel de negocios sin pasar por el flujo de dueño.',
    selectRoleTitle: 'Elegí con qué perfil entrar',
    selectRoleSubtitle: 'Si tu cuenta tiene más de un perfil, elegí el que vas a usar en esta sesión. Vamos a recordarlo en este dispositivo.',
    ownerRoleTitle: 'Dueño de mascota',
    ownerRoleDescription: 'Usá el menú principal para ver Inicio, Mascotas, Tienda, Servicios, Lugares y Perfil.',
    partnerRoleTitle: 'Aliado / negocio',
    partnerRoleDescription: 'Entrá al panel aliado para administrar tu negocio, reservas, productos y clientes.',
    adminRoleTitle: 'Administrador',
    adminRoleDescription: 'Accedé al panel interno para gestionar la plataforma.',
    roleSelectionSaved: 'Vamos a recordar tu elección en este dispositivo.',
    dontHaveAccount: '¿No tienes una cuenta?',
    alreadyHaveAccount: '¿Ya tienes una cuenta?',
    signOut: 'Cerrar sesión',
    forgotPassword: '¿Olvidaste tu contraseña?',
    rememberPassword: 'Recordar contraseña',
    
    // Home/Feed
    searchPets: 'Buscar mascotas...',
    likesCount: 'me gusta',
    viewComments: 'Ver los {count} comentarios',
    hoursAgo: 'h',
    noPostsYet: '¡Aún no hay publicaciones!',
    beFirstToPost: 'Sé el primero en compartir algo sobre tu mascota',
    loadingPosts: 'Cargando publicaciones...',
    
    // Pets
    addPet: 'Agregar mascota',
    yearsOld: 'años',
    addFirstPet: '¡Agrega tu primera mascota! 🐾',
    createPetProfile: 'Comienza creando el perfil de tu compañero peludo',
    loadingPets: 'Cargando mascotas...',
    petDetails: 'Detalles de la mascota',
    editPet: 'Editar mascota',
    deletePet: 'Eliminar mascota',
    petName: 'Nombre de la mascota',
    species: 'Especie',
    breed: 'Raza',
    age: 'Edad',
    weight: 'Peso',
    gender: 'Género',
    male: 'Macho',
    female: 'Hembra',
    neutered: 'Castrado/Esterilizado',
    hasChip: 'Tiene microchip',
    chipNumber: 'Número de microchip',
    description: 'Descripción',
    selectSpecies: 'Seleccionar especie',
    selectBreed: 'Seleccionar raza',
    dog: 'Perro',
    cat: 'Gato',
    ageYears: 'años',
    ageMonths: 'meses',
    ageDays: 'días',
    kg: 'kg',
    lb: 'lb',
    
    // Shop
    petShop: 'Tienda de Mascotas',
    addToCart: 'Agregar al carrito',
    reviews: 'reseñas',
    all: 'Todo',
    food: 'Comida',
    toys: 'Juguetes',
    accessories: 'Accesorios',
    healthCategory: 'Salud',
    hygiene: 'Higiene',
    noProductsAvailable: 'No hay productos disponibles',
    noProductsInCategory: 'No hay productos en esta categoría',
    loadingProducts: 'Cargando productos...',
    productDetails: 'Detalles del producto',
    price: 'Precio',
    stock: 'Stock',
    category: 'Categoría',
    brand: 'Marca',
    addToCartSuccess: 'Producto agregado al carrito',
    cart: 'Carrito',
    myCart: 'Mi Carrito',
    cartEmpty: 'Tu carrito está vacío',
    cartEmptySubtitle: 'Agrega productos de la tienda para comenzar tu compra',
    goToShop: 'Ir a la Tienda',
    quantity: 'Cantidad',
    subtotal: 'Subtotal',
    shipping: 'Envío',
    total: 'Total',
    checkout: 'Finalizar compra',
    shippingAddress: 'Dirección de envío',
    orderSummary: 'Resumen del pedido',
    payWithMercadoPago: 'Pagar con Mercado Pago',
    
    // Services
    petServices: 'Servicios para Mascotas',
    veterinary: 'Veterinario',
    grooming: 'Peluquería',
    walking: 'Paseo',
    boarding: 'Pensión',
    noServicesAvailable: 'No hay servicios disponibles',
    noBusinessInCategory: 'No hay negocios disponibles en esta categoría',
    loadingServices: 'Cargando servicios...',
    serviceDetails: 'Detalles del servicio',
    bookService: 'Reservar servicio',
    duration: 'Duración',
    location: 'Ubicación',
    contact: 'Contactar',
    bookingSuccess: 'Reserva realizada con éxito',
    selectPet: 'Selecciona tu mascota',
    selectDate: 'Selecciona una fecha',
    selectTime: 'Selecciona una hora',
    bookingNotes: 'Notas para el proveedor',
    confirmBooking: 'Confirmar reserva',
    signInToViewServices: 'Debes iniciar sesión para ver los servicios disponibles',
    
    // Profile
    editProfile: 'Editar perfil',
    partnerMode: 'Modo Aliado',
    partnerModeOn: 'Estás en modo Aliado. Puedes gestionar tus servicios y reservas.',
    partnerModeOff: 'Cambia a modo Aliado para ofrecer servicios a otros dueños de mascotas.',
    myStats: 'Mis estadísticas',
    pets: 'Mascotas',
    posts: 'Publicaciones',
    followers: 'Seguidores',
    following: 'Siguiendo',
    notifications: 'Notificaciones',
    privacySecurity: 'Privacidad y seguridad',
    helpSupport: 'Ayuda y soporte',
    language: 'Idioma',
    spanish: 'Español',
    english: 'Inglés',
    registerBusiness: 'Registrar Negocio',
    myOrders: 'Mis Pedidos',
    biometricAuth: 'Autenticación biométrica',
    profilePhoto: 'Foto de perfil',
    basicInfo: 'Información básica',
    fullNameLabel: 'Nombre completo',
    emailLabel: 'Correo electrónico',
    phoneLabel: 'Teléfono',
    addressLabel: 'Dirección',
    bioLabel: 'Biografía',
    saveChanges: 'Guardar cambios',
    profileUpdated: 'Perfil actualizado correctamente',
    adminMode: 'Modo Administrador',
    goToAdmin: 'Ir a Admin',
    pendingVerification: 'Pendiente de verificación',
    noBusinessRegistered: 'Sin negocio registrado',
    adminModeDescription: 'Accede al panel de administración para gestionar la plataforma.',
    requestUnderReview: 'Tu solicitud está siendo revisada por un administrador.',
    canRegisterBusiness: 'Puedes registrar uno o más negocios para ofrecer servicios a otros dueños de mascotas',
    enterCompleteAddress: 'Ingresa tu dirección completa',
    products: 'productos',
    shippingByStore: 'Envío por tienda',
    noShipping: 'Sin envío',
    calculating: 'Calculando',
    
    // Orders
    orders: 'Pedidos',
    orderHistory: 'Historial de pedidos',
    activeOrders: 'Pedidos activos',
    completedOrders: 'Pedidos completados',
    orderNumber: 'Número de pedido',
    orderDate: 'Fecha del pedido',
    orderStatus: 'Estado del pedido',
    orderTotal: 'Total del pedido',
    pending: 'Pendiente',
    confirmed: 'Confirmado',
    processing: 'En proceso',
    shipped: 'Enviado',
    delivered: 'Entregado',
    cancelled: 'Cancelado',
    trackOrder: 'Rastrear pedido',
    reorder: 'Reordenar',
    orderDetails: 'Detalles del pedido',
    
    // Health
    health: 'Salud',
    vaccines: 'Vacunas',
    illnesses: 'Enfermedades',
    allergies: 'Alergias',
    deworming: 'Desparasitaciones',
    weightTracking: 'Seguimiento de peso',
    addVaccine: 'Agregar vacuna',
    addIllness: 'Agregar enfermedad',
    addAllergy: 'Agregar alergia',
    addDeworming: 'Agregar desparasitación',
    addWeight: 'Agregar peso',
    vaccineName: 'Nombre de la vacuna',
    applicationDate: 'Fecha de aplicación',
    nextDueDate: 'Próxima dosis',
    veterinarian: 'Veterinario',
    notes: 'Notas',
    illnessName: 'Nombre de la enfermedad',
    diagnosisDate: 'Fecha de diagnóstico',
    treatment: 'Tratamiento',
    allergyName: 'Alérgeno',
    symptoms: 'Síntomas',
    severity: 'Severidad',
    productName: 'Producto utilizado',
    weightValue: 'Peso',
    weightUnit: 'Unidad',
    date: 'Fecha',
    
    // Albums
    albums: 'Álbumes',
    addPhotos: 'Agregar fotos',
    albumTitle: 'Título del álbum',
    albumDescription: 'Descripción del álbum',
    shareInFeed: 'Compartir en el feed',
    saveToAlbum: 'Guardar en álbum',
    takePhoto: 'Tomar foto',
    selectFromGallery: 'Seleccionar de galería',
    photosSelected: 'fotos seleccionadas',
    noAlbums: 'No hay álbumes creados',
    createFirstAlbum: 'Crea tu primer álbum de fotos',
    
    // Common
    loading: 'Cargando...',
    error: 'Error',
    fillAllFields: 'Por favor completa todos los campos',
    passwordsDontMatch: 'Las contraseñas no coinciden',
    passwordsMatch: 'Las contraseñas coinciden',
    passwordTooShort: 'La contraseña debe tener más de 8 caracteres',
    passwordRequirementsNotMet: 'La contraseña debe incluir minúscula, mayúscula, número, carácter especial y tener más de 8 caracteres',
    passwordStrength: 'Fortaleza',
    passwordStrengthWeak: 'Débil',
    passwordStrengthMedium: 'Media',
    passwordStrengthStrong: 'Fuerte',
    passwordRuleLowercase: 'Al menos una letra minúscula',
    passwordRuleUppercase: 'Al menos una letra mayúscula',
    passwordRuleNumber: 'Al menos un número',
    passwordRuleSpecialChar: 'Al menos un carácter especial',
    passwordRuleMinLength: 'Más de 8 caracteres',
    save: 'Guardar',
    cancel: 'Cancelar',
    delete: 'Eliminar',
    edit: 'Editar',
    add: 'Agregar',
    remove: 'Eliminar',
    confirm: 'Confirmar',
    back: 'Volver',
    next: 'Siguiente',
    previous: 'Anterior',
    close: 'Cerrar',
    open: 'Abrir',
    yes: 'Sí',
    no: 'No',
    ok: 'OK',
    retry: 'Reintentar',
    refresh: 'Actualizar',
    search: 'Buscar',
    filter: 'Filtrar',
    sort: 'Ordenar',
    view: 'Ver',
    share: 'Compartir',
    like: 'Me gusta',
    comment: 'Comentar',
    follow: 'Seguir',
    unfollow: 'Dejar de seguir',
    min: 'min',
    hour: 'hora',
    hours: 'horas',
    day: 'día',
    days: 'días',
    week: 'semana',
    weeks: 'semanas',
    month: 'mes',
    months: 'meses',
    year: 'año',
    today: 'Hoy',
    yesterday: 'Ayer',
    tomorrow: 'Mañana',
    now: 'Ahora',
    recently: 'Recientemente',
  },
  en: {
    // Navigation
    home: 'Home',
    myPets: 'My Pets',
    shop: 'Shop',
    services: 'Services',
    petFriendly: 'Pet Friendly',
    profile: 'Profile',
    
    // Auth
    welcomeBack: 'Welcome Back to DogCatiFy! 🐾',
    signInSubtitle: 'Sign in to connect with your pet community',
    joinPatitas: 'Join DogCatiFy! 🐾',
    createAccountSubtitle: 'Create your account and start connecting with pet lovers',
    email: 'Email',
    password: 'Password',
    confirmPassword: 'Confirm Password',
    fullName: 'Full Name',
    signIn: 'Sign In',
    signUp: 'Sign Up',
    createAccount: 'Create Account',
    becomePartner: 'Become a partner',
    partnerRegisterSubtitle: 'Create your partner account to access the business dashboard without going through the owner flow.',
    selectRoleTitle: 'Choose the profile to sign in with',
    selectRoleSubtitle: 'If your account has more than one profile, choose the one you want to use for this session. We will remember it on this device.',
    ownerRoleTitle: 'Pet owner',
    ownerRoleDescription: 'Use the main menu to access Home, Pets, Shop, Services, Places and Profile.',
    partnerRoleTitle: 'Partner / business',
    partnerRoleDescription: 'Enter the partner dashboard to manage your business, bookings, products and customers.',
    adminRoleTitle: 'Administrator',
    adminRoleDescription: 'Access the internal panel to manage the platform.',
    roleSelectionSaved: 'We will remember your choice on this device.',
    dontHaveAccount: "Don't have an account?",
    alreadyHaveAccount: 'Already have an account?',
    signOut: 'Sign Out',
    forgotPassword: 'Forgot your password?',
    rememberPassword: 'Remember password',
    
    // Home/Feed
    searchPets: 'Search pets...',
    likesCount: 'likes',
    viewComments: 'View {count} comments',
    hoursAgo: 'h',
    noPostsYet: 'No posts yet!',
    beFirstToPost: 'Be the first to share something about your pet',
    loadingPosts: 'Loading posts...',
    
    // Pets
    addPet: 'Add Pet',
    yearsOld: 'years old',
    addFirstPet: 'Add your first pet! 🐾',
    createPetProfile: 'Start by creating your furry companion\'s profile',
    loadingPets: 'Loading pets...',
    petDetails: 'Pet details',
    editPet: 'Edit pet',
    deletePet: 'Delete pet',
    petName: 'Pet name',
    species: 'Species',
    breed: 'Breed',
    age: 'Age',
    weight: 'Weight',
    gender: 'Gender',
    male: 'Male',
    female: 'Female',
    neutered: 'Neutered/Spayed',
    hasChip: 'Has microchip',
    chipNumber: 'Microchip number',
    description: 'Description',
    selectSpecies: 'Select species',
    selectBreed: 'Select breed',
    dog: 'Dog',
    cat: 'Cat',
    ageYears: 'years',
    ageMonths: 'months',
    ageDays: 'days',
    kg: 'kg',
    lb: 'lb',
    
    // Shop
    petShop: 'Pet Shop',
    addToCart: 'Add to Cart',
    reviews: 'reviews',
    all: 'All',
    food: 'Food',
    toys: 'Toys',
    accessories: 'Accessories',
    healthCategory: 'Health',
    hygiene: 'Hygiene',
    noProductsAvailable: 'No products available',
    noProductsInCategory: 'No products in this category',
    loadingProducts: 'Loading products...',
    productDetails: 'Product details',
    price: 'Price',
    stock: 'Stock',
    category: 'Category',
    brand: 'Brand',
    addToCartSuccess: 'Product added to cart',
    cart: 'Cart',
    myCart: 'My Cart',
    cartEmpty: 'Your cart is empty',
    cartEmptySubtitle: 'Add products from the store to start shopping',
    goToShop: 'Go to Shop',
    quantity: 'Quantity',
    subtotal: 'Subtotal',
    shipping: 'Shipping',
    total: 'Total',
    checkout: 'Checkout',
    shippingAddress: 'Shipping address',
    orderSummary: 'Order summary',
    payWithMercadoPago: 'Pay with Mercado Pago',
    
    // Services
    petServices: 'Pet Services',
    veterinary: 'Veterinary',
    grooming: 'Grooming',
    walking: 'Walking',
    boarding: 'Boarding',
    noServicesAvailable: 'No services available',
    noBusinessInCategory: 'No businesses available in this category',
    loadingServices: 'Loading services...',
    serviceDetails: 'Service details',
    bookService: 'Book service',
    duration: 'Duration',
    location: 'Location',
    contact: 'Contact',
    bookingSuccess: 'Booking successful',
    selectPet: 'Select your pet',
    selectDate: 'Select a date',
    selectTime: 'Select a time',
    bookingNotes: 'Notes for provider',
    confirmBooking: 'Confirm booking',
    signInToViewServices: 'You must sign in to view available services',
    
    // Profile
    editProfile: 'Edit Profile',
    partnerMode: 'Partner Mode',
    partnerModeOn: 'You are in Partner mode. You can manage your services and bookings.',
    partnerModeOff: 'Switch to Partner mode to offer services to other pet owners.',
    myStats: 'My Stats',
    pets: 'Pets',
    posts: 'Posts',
    followers: 'Followers',
    following: 'Following',
    notifications: 'Notifications',
    privacySecurity: 'Privacy & Security',
    helpSupport: 'Help & Support',
    language: 'Language',
    spanish: 'Spanish',
    english: 'English',
    registerBusiness: 'Register Business',
    myOrders: 'My Orders',
    biometricAuth: 'Biometric authentication',
    profilePhoto: 'Profile photo',
    basicInfo: 'Basic information',
    fullNameLabel: 'Full name',
    emailLabel: 'Email address',
    phoneLabel: 'Phone number',
    addressLabel: 'Address',
    bioLabel: 'Biography',
    saveChanges: 'Save changes',
    profileUpdated: 'Profile updated successfully',
    adminMode: 'Admin Mode',
    goToAdmin: 'Go to Admin',
    pendingVerification: 'Pending verification',
    noBusinessRegistered: 'No business registered',
    adminModeDescription: 'Access the admin panel to manage the platform.',
    requestUnderReview: 'Your request is being reviewed by an administrator.',
    canRegisterBusiness: 'You can register one or more businesses to offer services to other pet owners',
    enterCompleteAddress: 'Enter your complete address',
    products: 'products',
    shippingByStore: 'Shipping by store',
    noShipping: 'No shipping',
    calculating: 'Calculating',
    
    // Orders
    orders: 'Orders',
    orderHistory: 'Order history',
    activeOrders: 'Active orders',
    completedOrders: 'Completed orders',
    orderNumber: 'Order number',
    orderDate: 'Order date',
    orderStatus: 'Order status',
    orderTotal: 'Order total',
    pending: 'Pending',
    confirmed: 'Confirmed',
    processing: 'Processing',
    shipped: 'Shipped',
    delivered: 'Delivered',
    cancelled: 'Cancelled',
    trackOrder: 'Track order',
    reorder: 'Reorder',
    orderDetails: 'Order details',
    
    // Health
    health: 'Health',
    vaccines: 'Vaccines',
    illnesses: 'Illnesses',
    allergies: 'Allergies',
    deworming: 'Deworming',
    weightTracking: 'Weight tracking',
    addVaccine: 'Add vaccine',
    addIllness: 'Add illness',
    addAllergy: 'Add allergy',
    addDeworming: 'Add deworming',
    addWeight: 'Add weight',
    vaccineName: 'Vaccine name',
    applicationDate: 'Application date',
    nextDueDate: 'Next due date',
    veterinarian: 'Veterinarian',
    notes: 'Notes',
    illnessName: 'Illness name',
    diagnosisDate: 'Diagnosis date',
    treatment: 'Treatment',
    allergyName: 'Allergen',
    symptoms: 'Symptoms',
    severity: 'Severity',
    productName: 'Product used',
    weightValue: 'Weight',
    weightUnit: 'Unit',
    date: 'Date',
    
    // Albums
    albums: 'Albums',
    addPhotos: 'Add photos',
    albumTitle: 'Album title',
    albumDescription: 'Album description',
    shareInFeed: 'Share in feed',
    saveToAlbum: 'Save to album',
    takePhoto: 'Take photo',
    selectFromGallery: 'Select from gallery',
    photosSelected: 'photos selected',
    noAlbums: 'No albums created',
    createFirstAlbum: 'Create your first photo album',
    
    // Common
    loading: 'Loading...',
    error: 'Error',
    success: 'Success',
    fillAllFields: 'Please fill in all fields',
    passwordsDontMatch: 'Passwords do not match',
    passwordsMatch: 'Passwords match',
    passwordTooShort: 'Password must be longer than 8 characters',
    passwordRequirementsNotMet: 'Password must include lowercase, uppercase, number, special character and be longer than 8 characters',
    passwordStrength: 'Strength',
    passwordStrengthWeak: 'Weak',
    passwordStrengthMedium: 'Medium',
    passwordStrengthStrong: 'Strong',
    passwordRuleLowercase: 'At least one lowercase letter',
    passwordRuleUppercase: 'At least one uppercase letter',
    passwordRuleNumber: 'At least one number',
    passwordRuleSpecialChar: 'At least one special character',
    passwordRuleMinLength: 'More than 8 characters',
    save: 'Save',
    cancel: 'Cancel',
    delete: 'Delete',
    edit: 'Edit',
    add: 'Add',
    remove: 'Remove',
    confirm: 'Confirm',
    back: 'Back',
    next: 'Next',
    previous: 'Previous',
    close: 'Close',
    open: 'Open',
    yes: 'Yes',
    no: 'No',
    ok: 'OK',
    retry: 'Retry',
    refresh: 'Refresh',
    search: 'Search',
    filter: 'Filter',
    sort: 'Sort',
    view: 'View',
    share: 'Share',
    like: 'Like',
    comment: 'Comment',
    follow: 'Follow',
    unfollow: 'Unfollow',
    min: 'min',
    hour: 'hour',
    hours: 'hours',
    day: 'day',
    days: 'days',
    week: 'week',
    weeks: 'weeks',
    month: 'month',
    months: 'months',
    year: 'year',
    today: 'Today',
    yesterday: 'Yesterday',
    tomorrow: 'Tomorrow',
    now: 'Now',
    recently: 'Recently',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>('es');

  useEffect(() => {
    loadLanguage();
  }, []);

  const loadLanguage = async () => {
    try {
      const savedLanguage = await AsyncStorage.getItem('language');
      if (savedLanguage && (savedLanguage === 'es' || savedLanguage === 'en')) {
        setLanguageState(savedLanguage);
      }
    } catch (error) {
      console.error('Error loading language:', error);
    }
  };

  const setLanguage = async (lang: Language) => {
    try {
      await AsyncStorage.setItem('language', lang);
      setLanguageState(lang);
    } catch (error) {
      console.error('Error saving language:', error);
    }
  };

  const t = (key: string): string => {
    const keys = key.split('.');
    let value: any = translations[language];
    
    for (const k of keys) {
      value = value?.[k];
    }
    
    return value || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};
